_wandb:
    value:
        cli_version: 0.22.2
        e:
            feg09x8aqxr1v9fcv8v2lvly6n8yguyp:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "8589934592"
                codePath: tutorial/mappo_vmas_training.py
                codePathLocal: mappo_vmas_training.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "207749267456"
                email: sophieyoshi2014@gmail.com
                executable: /Users/sophiechiang/miniforge3/envs/vmas_fixed_env/bin/python
                git:
                    commit: 807a7cdf0d6136fa648ea7d285719b364ecf8b1e
                    remote: https://github.com/schiang28/football-rl.git
                host: Reginald-IV.local
                memory:
                    total: "8589934592"
                os: macOS-15.7.1-arm64-arm-64bit
                program: /Users/sophiechiang/Programming/Dissertation-II/tutorial/mappo_vmas_training.py
                python: CPython 3.11.14
                root: ./wandb_logs
                startedAt: "2025-11-03T21:17:06.414271Z"
                writerId: feg09x8aqxr1v9fcv8v2lvly6n8yguyp
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 61
            "4": 3.11.14
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
